// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "./Verifier.sol"; // The contract generated by EZKL

contract MonadPriceGuard {
    Verifier public verifier;
    address public owner;

    event PredictionVerified(address indexed prover, uint256[] inputs, uint256[] output, uint256 timestamp);

    constructor(address _verifierAddress) {
        verifier = Verifier(_verifierAddress);
        owner = msg.sender;
    }

    function verifyPrediction(
        uint256[] calldata instances, /* Public inputs/outputs */
        bytes calldata proof
    ) public returns (bool) {
        // On Monad, this execution is extremely fast and cheap
        // instances[0...n] usually contains the output (prediction) and inputs if public
        
        try verifier.verify(instances, proof) {
            // Verification successful
            emit PredictionVerified(msg.sender, instances, instances, block.timestamp);
            return true;
        } catch {
            revert("ZK Proof verification failed");
        }
    }
}

